# Confirmatory Data Analysis  Overview Example

CDA is a top-down approach in which we start with a question and use data to answer it.

1. **Experiments** are studies where the researchers explicitly assign treatments to cases (we wanted to generate this data intently)
2. **Observational Studies** are studies where no treatment has been explicitly applied (we look at past data)

**Intervention** is the term we use to describe the act of deliberately changing a variable in a system to observe the effect on other variables.

Making causal conclusions based on experiments is often reasonable, since we can randomly assign the explanatory variable(s), i.e., the treatments. However, making the same causal conclusions based on observational data can be treacherous and is not recommended.

Read more, if you are interested in: [Study design (IMS book)](https://openintro-ims.netlify.app/data-design).

## Experiment: Blind Typing

An experiment aims to confirm a hypothesis using data. Hence, we are doing CDA.

In this experiment, we want to test people who claim that they type without looking at their keyboard. Let's verify their claim. The words-per-minute typed should not significantly drop if we turn off the lights.

1. We will test our typing with the **lights on**
2. Then, we'll test again with the **lights off**

Now let's jump to action..

### Data Collection

- Experiment subjects will visit the website: https://monkeytype.com/ to undergo the typing test
- Each subject will report their own score. Which we will store down below

### Data Loading

We will use regular Python lists to store the measurements before and after the intervention.

In [2]:
# Experiment Data
scores_1 = [33, 46, 35, 28, 20, 22, 19, 25, 19, 67, 23, 19, 40, 18, 27, 44]
scores_2 = [46, 23, 36, 21, 38, 23, 22, 27, 28, 37, 37, 26, 33, 53, 9, 13]

### Verification

We expect the same participants to undergo the experiment once with the lights on and once with the lights out.

In [3]:
# Quick Check
assert len(scores_1) == len(scores_2)

### Enter: `pandas.Series`

In Python, libraries like Pandas include data-structures and algorithms (collectively as objects) to perform calculations efficiently on lists and tables, also known as: **Series** and **DataFrames** respectively.

In [4]:
import pandas as pd

s1 = pd.Series(scores_1, name="wpm")
s1[:10]

0    33
1    46
2    35
3    28
4    20
5    22
6    19
7    25
8    19
9    67
Name: wpm, dtype: int64

Statistics:

In [5]:
print("Number of items:", len(s1))
print("Sum:", s1.sum())
print("Average:", s1.mean())
print("Median:", s1.median(),)
print("Mode:", s1.mode()[0])
print("Standard Deviation:", s1.std())

Number of items: 16
Sum: 485
Average: 30.3125
Median: 26.0
Mode: 19
Standard Deviation: 13.444794531713752

Also the largest:

In [6]:
s1.nlargest(3)

9     67
1     46
15    44
Name: wpm, dtype: int64

..and smallest values:

In [7]:
s1.nsmallest(3)

13    18
6     19
8     19
Name: wpm, dtype: int64

### Enter: `pandas.DataFrame`

- DataFrame represents tables, of multiple columns
- Let's combine the results of with and without intervention:

In [15]:
df = pd.DataFrame({
    "wpm": scores_1 + scores_2,
    "intervention": (
        [False] * len(scores_1) +
        [True] * len(scores_2)
    )
})

In [9]:
df.head()

   wpm  intervention
0   33         False
1   46         False
2   35         False
3   28         False
4   20         False

In [10]:
df.tail()

    wpm  intervention
27   26          True
28   33          True
29   53          True
30    9          True
31   13          True

### Overall statistics

In [11]:
df.describe().T

     count      mean        std  min    25%   50%   75%   max
wpm   32.0  29.90625  12.321917  9.0  21.75  27.0  37.0  67.0

### Statistics by group

In [12]:
df.groupby(by='intervention').describe()

               wpm
             count     mean        std   min    25%   50%    75%   max
intervention
False         16.0  30.3125  13.444795  18.0  19.75  26.0  36.25  67.0
True          16.0  29.5000  11.518102   9.0  22.75  27.5  37.00  53.0

### Visualization: `Seaborn`

**Seaborn** is a visualization library specifically built for statistical plots. We'll use it to render the **Box-and-whiskers Plot** which visualizes the statistics described in the summary table above.

In [13]:
import seaborn as sns

sns.catplot(
    data=df,
    kind='box',
    x='wpm',
    y='intervention',
    orient='h',
    height=3, # vertical scale
    aspect=2  # Maintain proportion
)

ModuleNotFoundError: No module named 'seaborn'

### Experiment Outcome

Question to be answered by inferential statistics: **is this difference significant?**